//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceWithAutofacAndLog4Net_Client.WCFServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dto", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceWithAutofacAndLog4Net.Transvers" +
        "al")]
    [System.SerializableAttribute()]
    public partial class Dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Num1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Num2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Num1 {
            get {
                return this.Num1Field;
            }
            set {
                if ((this.Num1Field.Equals(value) != true)) {
                    this.Num1Field = value;
                    this.RaisePropertyChanged("Num1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Num2 {
            get {
                return this.Num2Field;
            }
            set {
                if ((this.Num2Field.Equals(value) != true)) {
                    this.Num2Field = value;
                    this.RaisePropertyChanged("Num2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServer.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Suma", ReplyAction="http://tempuri.org/IService/SumaResponse")]
        decimal Suma(WcfServiceWithAutofacAndLog4Net_Client.WCFServer.Dto values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Suma", ReplyAction="http://tempuri.org/IService/SumaResponse")]
        System.Threading.Tasks.Task<decimal> SumaAsync(WcfServiceWithAutofacAndLog4Net_Client.WCFServer.Dto values);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WcfServiceWithAutofacAndLog4Net_Client.WCFServer.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WcfServiceWithAutofacAndLog4Net_Client.WCFServer.IService>, WcfServiceWithAutofacAndLog4Net_Client.WCFServer.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Suma(WcfServiceWithAutofacAndLog4Net_Client.WCFServer.Dto values) {
            return base.Channel.Suma(values);
        }
        
        public System.Threading.Tasks.Task<decimal> SumaAsync(WcfServiceWithAutofacAndLog4Net_Client.WCFServer.Dto values) {
            return base.Channel.SumaAsync(values);
        }
    }
}
